package org.entirej.forms.constants;

/*
 * AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the entirej plugin from the form.
 * It should not be modified by hand.
 */
public class F_TEST_FULL_CALENDAR_EVENT
{
    public static final String ID = "testFullCalendarEvent";

    public static class B_TEST
    {
        public static final String ID         = "Test";
        public static final String I_ID       = "id";
        public static final String I_NOTE     = "note";
        public static final String I_EDITABLE = "editable";
        public static final String I_TITLE    = "title";
        public static final String I_START    = "start";
        public static final String I_END      = "end";
        public static final String I_ALL_DAY  = "allDay";

    }

    public static class B_EDIT_EVENT_REQ
    {
        public static final String ID      = "EditEventReq";
        public static final String I_TITLE = "title";
        public static final String I_START = "start";
        public static final String I_END   = "end";

    }

    public static final String C_MAIN           = "MAIN";
    public static final String C_EDIT_EVENT     = "EDIT_EVENT";
    public static final String C_EDIT_EVENT_REQ = "EditEventReq";

}