package org.entirej.constants;

/*
 * AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the entirej plugin from the
 * EntireJProperties. It should not be modified by hand.
 */
public class EJ_PROPERTIES
{
    public static final String M_DEFAULT    = "Default";

    public static final String VA_EVENT     = "event";
    public static final String VA_SUB_EVENT = "sub_event";

}